In [1]:
import numpy as np

data = np.loadtxt('chocolate_rating.csv', delimiter=',')
print(f'차원: {data.ndim}')
print(f'모양: {data.shape}')
print(f'원소 수: {data.size}')
print(data)

차원: 2
모양: (1795, 4)
원소 수: 7180
[[1.000e+00 2.016e+03 6.300e-01 3.750e+00]
 [2.000e+00 2.015e+03 7.000e-01 2.750e+00]
 [3.000e+00 2.015e+03 7.000e-01 3.000e+00]
 ...
 [1.793e+03 2.011e+03 6.500e-01 3.500e+00]
 [1.794e+03 2.011e+03 6.200e-01 3.250e+00]
 [1.795e+03 2.010e+03 6.500e-01 3.000e+00]]


In [3]:
print(data[:,3].mean())

3.185933147632312


In [5]:
high_level = data[data[:,3] >=4]
high_id = high_level[:,0].astype(np.int64)
print(f'우수 초콜릿 수: {high_id.size}')
print(high_id)

우수 초콜릿 수: 100
[  10   18   21   55   57   77   78   79   84   87   88   93  108  109
  118  124  153  180  181  187  223  232  233  240  243  244  245  248
  257  312  316  317  358  437  503  567  573  574  582  601  650  687
  690  691  701  720  730  800  828  862  864  865  866  883  919  993
 1088 1089 1118 1119 1120 1204 1241 1245 1247 1274 1277 1278 1289 1291
 1293 1295 1323 1331 1336 1378 1394 1426 1428 1433 1479 1488 1513 1516
 1529 1530 1531 1533 1536 1537 1544 1545 1664 1683 1686 1688 1694 1700
 1740 1757]


In [7]:
high_kakao = high_level[:,2]
unique_value, value_counts = np.unique(high_kakao, 
          return_counts=True)
print(f'카카오 함유량: {unique_value}')
print(f'함유량 빈도수: {value_counts}')

카카오 함유량: [0.6  0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7  0.71 0.72 0.73 0.74 0.75
 0.78 0.8  0.88]
함유량 빈도수: [ 1  3  4  2  1  3  2  2 45  1 11  1  4 17  1  1  1]


In [8]:
max_index = np.argmax(value_counts)
print(unique_value[max_index])
print(f'우수 초콜릿 {high_id.size}개 중에서 {value_counts[max_index]}개의 카카오 함유량이 {unique_value[max_index] *100}%입니다.')

0.7
우수 초콜릿 100개 중에서 45개의 카카오 함유량이 70.0%입니다.


In [10]:
unique_value = np.unique(high_kakao, return_counts=True)
value_counts = np.unique(high_kakao, return_counts=True)
print(f'카카오 함유량: {unique_value}')
print(f'함유량 빈도수: {value_counts}')

카카오 함유량: (array([0.6 , 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72,
       0.73, 0.74, 0.75, 0.78, 0.8 , 0.88]), array([ 1,  3,  4,  2,  1,  3,  2,  2, 45,  1, 11,  1,  4, 17,  1,  1,  1]))
함유량 빈도수: (array([0.6 , 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72,
       0.73, 0.74, 0.75, 0.78, 0.8 , 0.88]), array([ 1,  3,  4,  2,  1,  3,  2,  2, 45,  1, 11,  1,  4, 17,  1,  1,  1]))
