In [1]:
import numpy as np

list1 = [1,2,3,4]
print(type(list1))
a = np.array(list1)
print(type(a))
print(a.shape)

<class 'list'>
<class 'numpy.ndarray'>
(4,)


In [7]:
[
    [1,2,3],
    [4,5,6]
]
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0, 1])
print(b[1])

(2, 3)
2
[4 5 6]


In [ ]:
# np.array() # 리스트를 배열로 변환
# np.arrange() # 파이썬의 range와 유사하며 일정한 간격의 수를 배열로 반환
# np.ones() # 모든 데이터를 1로채운 n차원 배열 생성
# np.zeros() # 모든 데이터를 0으로 채운 n차원 배열 생성
# np.empty() # 초기화하지 않은 n차원 배열생성
# np.eye() or np.identity() # 대각선에만 1을 채우고 그 외에는 0으로 채우는 2차원 배열 one hot encoding
# np.linespace() #초기값부터 최종값까지 지정한 간격의 수를 채워 배열을 생성
# np.full() #지정한 모양에 지정한 값으로 채운 배열을 생성

In [14]:
a = np.arange(0,10,2) #0부터 10까지 짝수만
d = np.arange(0.,10.,2) #0부터 10까지 짝수만 .으로 정리
c = np.arange(0,10,3) #0부터 10까지 3d의배수만
b = np.arange(5,10,1) #5부터 10까지
print(a)
print(b)
print(c)
print(d)

[0 2 4 6 8]
[5 6 7 8 9]
[0 3 6 9]
[0. 2. 4. 6. 8.]


In [22]:
a = np.ones(7)
b = np.ones((3,4))
print(a)
print(b)

[1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [20]:
# alt + shift +b 새로운 창 생성
c = np.full((4,3),5) #full은 앞 ()형태를 , 5로 채우겠다 라는 말
print(c)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [23]:
d = np.eye(4) #보통은 eye를 더 많이씀
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [25]:
d = np.identity(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [34]:
a = np.eye(4, dtype=int) #원래는 double 형태인데 datatype을 int로 바꾸면 실수형으로 바뀜
# a = np.eye(4, dtype=np.float64) 
print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [35]:
e = np.array([1,2], dtype=np.float64)
print(e.dtype)

float64


In [36]:
# 넘파이 속성 ndarray는 다음과 같은 속성을 갖는다.
# ndim : 차원 수
# dtype : 요소의 자료형
# itemsize : 요소저장용량
# size: 요소 수
# nbytes: 배열 저장용량
# T: 행과 열을 교차
# shape: 배열의 모양(차원고나 요소의수를 알수있다)

arr = np.array([[0,1,2],[3,4,5]])
print(f'type(arr):{type(arr)}')
print(f'arr.ndim:{(arr.ndim)}')
print(f'arr.dtype:{(arr.dtype)}')
print(f'arr.itemsize:{(arr.itemsize)}')
print(f'arr.size:{(arr.size)}')
print(f'arr.nbytes:{(arr.nbytes)}')
print(f'arr.T:{(arr.T)}')
print(f'arr.shape:{(arr.shape)}')

type(arr):<class 'numpy.ndarray'>
arr.ndim:2
arr.dtype:int64
arr.itemsize:8
arr.size:6
arr.nbytes:48
arr.T:[[0 3]
 [1 4]
 [2 5]]
arr.shape:(2, 3)


In [43]:
aa = np.full((3,4,5),7)
print(aa)
print("@@@@@@@@@@@@@@@@@@@@@@ 구분선@@@@@@@@@@@@@@@@@@@@@@@@@@")
print(np.reshape(aa, (6,10)))
# 차원 축소 2차원을 1차원으로

[[[7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]]

 [[7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]]

 [[7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]]]
@@@@@@@@@@@@@@@@@@@@@@ 구분선@@@@@@@@@@@@@@@@@@@@@@@@@@
[[7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]]


In [45]:
# flatten() 1차원배열로 변경
# resize(i,j) 배열의 모양을 i*j로 변경
# transpose() 열과 행을 교차 np.T와 유사

aaa=np.arange(8)
print(aaa.shape)
aaa.shape = (2,4)
print(aaa.shape)
print(aaa.flatten())
aaa.resize(4,2)
print(aaa.shape)
print(aaa)


(8,)
(2, 4)
[0 1 2 3 4 5 6 7]
(4, 2)
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [10]:
# 0부터 9까지 정수 ㄷ ㅔ이터를 넣은 넘파원 1차원 배열을 생성
# 2행 5열로 변형

import numpy as np

a=np.arange(10)
# a = np.arange(0,10)
a.resize(2,5)
print(a)

a = np.array(range(10))
b = a.reshape((2,5))
print(b)
c = np.arange(10)
c.shape = (2,5)
print(c)
print(c.transpose())

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [12]:
list = [[1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12]] 
# 위 list를 넘파이 배열로 변환하여 두번째행부터 세번째행까지, 첫번째열부터 두번째열까지 출력하시오 슬라이싱
# 행 세로 열 가로
# 리스트를 넘파이 배열로 변환
a = np.array(list)

# 두 번째 행부터 세 번째 행까지, 첫 번째 열부터 두 번째 열까지 출력
print(a[1:3, 0:2])

[[4 5]
 [7 8]]


In [13]:
mask = np.array([0, 1, 0, 1], dtype=bool)
mask = np.array([False, True, False, True])
data = np.random.randn(4,2)
print(data)

print(f'마스킹된 데이터 출력: \n{data[mask]}')

[[-0.23206021 -1.0469924 ]
 [ 0.70180849  0.54395505]
 [-0.38238269 -1.34228726]
 [-0.06873643  0.8406898 ]]
마스킹된 데이터 출력: 
[[ 0.70180849  0.54395505]
 [-0.06873643  0.8406898 ]]


In [14]:
print(data[data<0])

[-0.23206021 -1.0469924  -0.38238269 -1.34228726 -0.06873643]


In [15]:
print(data[1][data[1]>0]) #ㄷㅔ이터 첫번째가 0보다 큰거 마스킹중

[0.70180849 0.54395505]


In [16]:
# 배열복사
# 얕은 복사 등호(=)를 이용, 복사가 아니라 주소값이 복사
# 깊은 복사 copy()를 이용, 새로운 복사본이 만들어짐

a =np.arange(6) #[0,1,2,3,4,5]
b =a
b[1]=3
print(b)
print(a)

[0 3 2 3 4 5]
[0 3 2 3 4 5]


In [17]:
a =np.arange(6)  #[0,1,2,3,4,5]
b =a.copy()
b[1]=3
print(b)
print(a)

[0 3 2 3 4 5]
[0 1 2 3 4 5]


In [18]:
# 정렬
a=np.array([4,8,1,0,9,3,5])
print(a)
print(np.sort(a))
print(a)

[4 8 1 0 9 3 5]
[0 1 3 4 5 8 9]
[4 8 1 0 9 3 5]
